#!/bin/sh
VER="1.02"

# v1.01 08-May-2020 Martineau Allow dnsmasq bypass; (Stop dnsmasq to release '127.0.0.1@53')
# v1.02 04-Feb-2021 Use service-event (for restart diskmon) rather than an explicit NTPD 'blocking' spin-loop i.e. 'nvram get ntp_ready=1'

# Create/use the appropriate service-event script method	# v1.02
if [ -z "$(grep -F "unbound_manager" /jffs/scripts/service-event)" ] || [ ! -f /jffs/scripts/service-event ];then	# v1.02
	[ ! -f /jffs/scripts/service-event ] && { echo -e "#!/bin/sh" > /jffs/scripts/service-event; chmod +x /jffs/scripts/service-event; }	# v1.02		

			# if [ -n "$(grep -F "sh /jffs/scripts/$SERVICE_SCRIPT_NAME" /jffs/scripts/service-event)" ];then
				# if [ ! -f /jffs/scripts/restart-diskmon ];then
					# echo -e "#!/bin/sh\n" > /jffs/scripts/restart-diskmon
					# chmod +x /jffs/scripts/restart-diskmon
				# fi
				# echo -e "/opt/etc/init.d/S61unbound start &\t\t# unbound_manager (/init.d/S61unbound)" >> /jffs/scripts/restart-diskmon		
			# else
				[ -n "$(grep -F "unbound_manager" /jffs/scripts/service-event)" ] && sed '/unbound_manager/d' /jffs/scripts/service-event
				echo -e "if [ \"\$1\" == \"restart\" ] && [ \"\$2\" == \"diskmon\" ];then /opt/etc/init.d/S61unbound start &; fi\t# unbound_manager (/init.d/S61unbound)" >> /jffs/scripts/service-event 
#			fi
fi

[ "$(nvram get ntp_ready)" = "0" ] && { logger -st "S61unbound" "Waiting for service-event 'rc_service: ntpd_synced nnnn:notify_rc restart_diskmon'"; exit 0; }	# v1.02

if [ "$1" = "start" ] || [ "$1" = "restart" ];then

		# http://www.snbforums.com/threads/mounting-issues-with-add-ons.69807/post-658396
		# v1.02 Use service-event for diskmon rather than a 'blocking' spin-loop
			# Wait for NTP before starting
			# ntptimer=0
			# while [ "$(nvram get ntp_ready)" = "0" ] && [ "$ntptimer" -lt "300" ]; do
					# ntptimer=$((ntptimer+1))
					# [ "$ntptimer" -eq "1" ] && logger -st "S61unbound" "Waiting for NTP to sync before starting Unbound..."
					# sleep 1
			# done

			# if [ "$ntptimer" -ge "300" ]; then
					# logger -st "S61unbound" "NTP failed to sync after 5 minutes - please check immediately!"
					# exit 1
			# fi
		
		TXT=
		# Default unbound+dnsmasq uses 'port: 53535'; if not then assume dnsmasq bypass ('port 53')
		[ -z "$(grep "^port: 53535" /opt/var/lib/unbound/unbound.conf)" ] && { service stop_dnsmasq; TXT="(bypass dnsmasq)"; } # v1.01 (Release '127.0.0.1@53')
		
        logger -t S61unbound "$1 Unbound DNS server $TXT $0"		
fi


# set environment PATH to system binaries
export PATH=/sbin:/bin:/usr/sbin:/usr/bin:$PATH
export TZ=$(cat /etc/TZ)
ENABLED=yes
PROCS=unbound
ARGS="-c /opt/var/lib/unbound/unbound.conf"
PREARGS="nohup"
PRECMD=""
POSTCMD="service restart_dnsmasq"
DESC=$PROCS
PATH=/opt/sbin:/opt/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

. /opt/etc/init.d/rc.func
